DROP TABLE IF EXISTS avaliacoes_auditoria       CASCADE;
DROP TABLE IF EXISTS usuarios_auditoria         CASCADE;
DROP TABLE IF EXISTS avaliacoes_outros_recursos CASCADE;
DROP TABLE IF EXISTS avaliacoes_equipamentos    CASCADE;
DROP TABLE IF EXISTS avaliacoes                 CASCADE;
DROP TABLE IF EXISTS usuarios                   CASCADE;

CREATE TABLE usuarios (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          TEXT            NOT NULL,
    email         VARCHAR(255)    NOT NULL UNIQUE,
    username      VARCHAR(50)     NOT NULL UNIQUE,
    senha_hash    TEXT            NOT NULL,
    is_admin      BOOLEAN         NOT NULL DEFAULT FALSE,
    precisa_trocar_senha BOOLEAN  NOT NULL DEFAULT TRUE,
    ativo         BOOLEAN         NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avaliacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Dados da equipe
    equipe TEXT,
    responsavel_avaliacao TEXT,

    -- Dados do cliente
    cliente_nome TEXT NOT NULL,
    objeto TEXT,
    local TEXT,
    data_avaliacao DATE NOT NULL,
    contato TEXT,
    email_cliente TEXT,

    -- Escopo e características gerais
    escopo_texto TEXT,
    servico_fora_montes_claros BOOLEAN,
    servico_intermediario BOOLEAN,

    -- Quantitativo 01 - Patch Panel / Cabeamento
    q1_categoria_cab VARCHAR(10),
    q1_blindado BOOLEAN,
    q1_novo_patch_panel BOOLEAN,
    q1_incluir_guia BOOLEAN,
    q1_qtd_pontos_rede INTEGER,
    q1_qtd_cabos INTEGER,
    q1_qtd_portas_patch_panel INTEGER,
    q1_qtd_patch_cords INTEGER,

    -- Quantitativo 02 - Switch
    q2_novo_switch BOOLEAN,
    q2_switch_poe BOOLEAN,
    q2_rede_industrial BOOLEAN,
    q2_qtd_pontos_rede INTEGER,
    q2_qtd_portas_switch INTEGER,
    q2_observacoes TEXT,

    -- Quantitativo 03 – Cabeamento Óptico
    q3_tipo_fibra VARCHAR(10),
    q3_qtd_fibras_por_cabo INTEGER,
    q3_tipo_conector VARCHAR(10),
    q3_novo_dio BOOLEAN,
    q3_caixa_terminacao BOOLEAN,
    q3_tipo_cabo_optico VARCHAR(20),
    q3_caixa_emenda BOOLEAN,
    q3_qtd_cabos INTEGER,
    q3_tamanho_total_m NUMERIC(10,2),
    q3_qtd_fibras INTEGER,
    q3_qtd_portas_dio INTEGER,
    q3_qtd_cordoes_opticos INTEGER,
    q3_observacoes TEXT,

    -- Quantitativo 04 – Equipamentos (flags gerais)
    q4_camera BOOLEAN,
    q4_nvr_dvr BOOLEAN,
    q4_access_point BOOLEAN,
    q4_conversor_midia BOOLEAN,
    q4_gbic BOOLEAN,
    q4_switch BOOLEAN,

    -- Quantitativo 05 – Infraestrutura
    q5_nova_eletrocalha BOOLEAN,
    q5_novo_eletroduto BOOLEAN,
    q5_novo_rack BOOLEAN,
    q5_instalacao_eletrica BOOLEAN,
    q5_nobreak BOOLEAN,
    q5_serralheria BOOLEAN,

    -- Localização / Referências
    localizacao_imagem1_url TEXT,
    localizacao_imagem2_url TEXT,

    -- Pré-requisitos
    pre_trabalho_altura BOOLEAN,
    pre_plataforma BOOLEAN,
    pre_plataforma_modelo TEXT,
    pre_plataforma_dias INTEGER,
    pre_fora_horario_comercial BOOLEAN,
    pre_veiculo_nortetel BOOLEAN,
    pre_container_materiais BOOLEAN,

    -- Novos campos - dias normais por função
    encarregado_dias INTEGER,
    instalador_dias INTEGER,
    auxiliar_dias INTEGER,
    tecnico_de_instalacao_dias INTEGER,
    tecnico_em_seguranca_dias INTEGER,

    -- Novos campos - horas extras por função
    encarregado_hora_extra INTEGER,
    instalador_hora_extra INTEGER,
    auxiliar_hora_extra INTEGER,
    tecnico_de_instalacao_hora_extra INTEGER,
    tecnico_em_seguranca_hora_extra INTEGER,

    -- Novos campos - trabalho em domingos/feriados por função
    encarregado_trabalho_domingo INTEGER,
    instalador_trabalho_domingo INTEGER,
    auxiliar_trabalho_domingo INTEGER,
    tecnico_de_instalacao_trabalho_domingo INTEGER,
    tecnico_em_seguranca_trabalho_domingo INTEGER,

    -- Novos campos - alimentação
    almoco_qtd INTEGER,
    lanche_qtd INTEGER,

    -- Novos campos - cronograma e prazos (espelho dos antigos 'prazo_*')
    cronograma_execucao BOOLEAN,
    dias_instalacao INTEGER,
    as_built BOOLEAN,
    dias_entrega_relatorio INTEGER,
    art BOOLEAN,
    tipo_formulario VARCHAR(50),

    -- Status e controle
    status VARCHAR(30) NOT NULL DEFAULT 'aberto',
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avaliacoes_equipamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE,
    equipamento TEXT NOT NULL,
    modelo TEXT,
    quantidade INTEGER NOT NULL,
    fabricante TEXT
);

CREATE TABLE avaliacoes_outros_recursos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE,
    descricao TEXT NOT NULL,
    quantidade INTEGER NOT NULL
);

CREATE TABLE avaliacoes_auditoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE,
    usuario VARCHAR(255),
    acao VARCHAR(50) NOT NULL,
    detalhes TEXT,
    data_hora TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios_auditoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_alvo_id INTEGER NOT NULL REFERENCES usuarios(id),
    usuario_acao_id INTEGER REFERENCES usuarios(id),
    acao VARCHAR(50) NOT NULL,
    detalhes TEXT,
    data_hora TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);