DROP TABLE IF EXISTS avaliacoes_auditoria       CASCADE;
DROP TABLE IF EXISTS usuarios_auditoria         CASCADE;
DROP TABLE IF EXISTS avaliacoes_outros_recursos CASCADE;
DROP TABLE IF EXISTS avaliacoes_equipamentos    CASCADE;
DROP TABLE IF EXISTS avaliacoes_fotos           CASCADE;
DROP TABLE IF EXISTS avaliacoes                 CASCADE;
DROP TABLE IF EXISTS usuarios                   CASCADE;

CREATE TABLE usuarios (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          TEXT            NOT NULL,
    email         VARCHAR(255)    NOT NULL UNIQUE,
    username      VARCHAR(50)     NOT NULL UNIQUE,
    senha_hash    TEXT            NOT NULL,
    is_admin      BOOLEAN         NOT NULL DEFAULT FALSE,
    precisa_trocar_senha BOOLEAN  NOT NULL DEFAULT TRUE,
    ativo         BOOLEAN         NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avaliacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- chave primária numérica da avaliação

    codigo_avaliacao VARCHAR(20) UNIQUE,                      -- código amigável da avaliação (ex.: AVT2025001), único por tabela

    -- Dados da equipe
    equipe TEXT,
    responsavel_avaliacao TEXT,

    -- Dados do cliente
    cliente_nome TEXT NOT NULL,
    objeto TEXT,
    local TEXT,
    data_avaliacao DATE NOT NULL,
    contato TEXT,
    email_cliente TEXT,

    -- Escopo e características gerais
    escopo_texto TEXT,
    servico_fora_montes_claros BOOLEAN,
    servico_intermediario BOOLEAN,

    -- Quantitativo 01 - Patch Panel / Cabeamento UTP
    q1_categoria_cab VARCHAR(10),                -- categoria do cabeamento (ex.: CAT5E, CAT6)
    q1_blindado BOOLEAN,                         -- indica se o cabo é blindado
    q1_novo_patch_panel BOOLEAN,                 -- indica se será fornecido um novo patch panel
    q1_incluir_guia BOOLEAN,                          -- indica se devem ser incluídas guias de cabos (Sim/Não)
    q1_qtd_guias_cabos INTEGER,                       -- quantidade de guias de cabos (preenchido apenas quando incluir_guia = true)
    q1_qtd_pontos_rede INTEGER,                  -- quantidade de pontos de rede
    q1_qtd_cabos INTEGER,                        -- quantidade de cabos UTP
    q1_qtd_portas_patch_panel INTEGER,           -- quantidade de portas do patch panel
    q1_qtd_patch_cords INTEGER,                  -- quantidade total de patch cords previstos
    q1_marca_cab VARCHAR(50),                    -- marca do cabeamento UTP (CommScope, Furukawa ou "Outro: <texto>")
    q1_qtd_guias_cabos INTEGER,                  -- quantidade de guias de cabos a instalar
    q1_patch_cords_modelo TEXT,                     -- modelo dos patch cords (0,5 mt; 1,5 mt; 3,0 mt; 5mt; 10mt; 15mt ou valor legado)
    q1_patch_cords_cor VARCHAR(50),                 -- cor dos patch cords (branco, amarelo, cinza, vermelho, azul ou valor legado)
    q1_patch_panel_existente_nome TEXT,          -- identificação do patch panel existente quando não houver novo fornecimento

    -- Quantitativo 02 - Switch
    q2_novo_switch BOOLEAN,                      -- indica se será fornecido um novo switch
    q2_switch_poe BOOLEAN,                       -- LEGADO - indicador de switch PoE, não utilizado nos novos formulários
    q2_rede_industrial BOOLEAN,                  -- LEGADO - indicador de rede industrial, não utilizado nos novos formulários
    q2_qtd_pontos_rede INTEGER,                  -- LEGADO - dimensionamento antigo de pontos de rede
    q2_qtd_portas_switch INTEGER,                -- LEGADO - dimensionamento antigo de portas de switch
    q2_fornecedor_switch VARCHAR(20),            -- quem fornece o switch: 'nortetel' ou 'cliente'
    q2_modelo_switch TEXT,                       -- modelo do switch (novo ou existente)
    q2_switch_foto_url TEXT,                     -- URL/caminho da foto do switch
    q2_switch_existente_nome TEXT,               -- identificação do switch existente quando não for novo
    q2_observacoes TEXT,                         -- observações gerais sobre o switch

    -- Quantitativo 03 – Cabeamento Óptico
    q3_tipo_fibra VARCHAR(10),                   -- tipo de fibra (ex.: MM, SM)
    q3_qtd_fibras_por_cabo INTEGER,              -- quantidade de fibras por cabo
    q3_tipo_conector VARCHAR(10),                -- tipo de conector (ex.: LC, SC)
    q3_novo_dio BOOLEAN,                         -- indica se será fornecido um novo DIO
    q3_caixa_terminacao BOOLEAN,                 -- indica se haverá caixa de terminação
    q3_tipo_cabo_optico VARCHAR(20),             -- tipo de cabo óptico
    q3_caixa_emenda BOOLEAN,                     -- indica se haverá caixa de emenda
    q3_qtd_cabos INTEGER,                        -- quantidade de cabos ópticos
    q3_tamanho_total_m NUMERIC(10,2),            -- metragem total estimada dos cabos ópticos
    q3_qtd_fibras INTEGER,                       -- quantidade total de fibras
    q3_qtd_portas_dio INTEGER,                   -- quantidade de portas do DIO
    q3_qtd_cordoes_opticos INTEGER,              -- quantidade de cordões ópticos
    q3_marca_cab_optico VARCHAR(50),             -- marca do cabeamento óptico
    q3_modelo_dio TEXT,                          -- modelo do DIO
    q3_modelo_cordao_optico TEXT,                -- modelo/descrição dos cordões ópticos
    q3_observacoes TEXT,                         -- observações gerais sobre cabeamento óptico

    -- Quantitativo 04 – Equipamentos (Câmeras, NVR/DVR, conversor, GBIC)
    q4_camera BOOLEAN,                           -- indica se a avaliação envolve câmeras
    q4_nvr_dvr BOOLEAN,                          -- indica se há NVR ou DVR
    q4_access_point BOOLEAN,                     -- LEGADO - flag genérica para Access Points
    q4_conversor_midia BOOLEAN,                  -- indica se há conversor de mídia
    q4_gbic BOOLEAN,                             -- indica se há GBIC
    q4_switch BOOLEAN,                           -- LEGADO - flag genérica para switches adicionais
    q4_conversor_midia_modelo TEXT,              -- modelo do conversor de mídia
    q4_gbic_modelo TEXT,                         -- modelo do GBIC
    q4_camera_nova BOOLEAN,                      -- indica se as câmeras são novas (caso contrário, realocação)
    q4_camera_modelo TEXT,                       -- modelo das câmeras
    q4_camera_qtd INTEGER,                       -- quantidade de câmeras
    q4_camera_fornecedor VARCHAR(20),            -- quem fornece as câmeras: 'nortetel' ou 'cliente'
    q4_nvr_dvr_modelo TEXT,                      -- modelo do NVR ou DVR

    -- Quantitativo 05 – Infraestrutura
    q5_nova_eletrocalha BOOLEAN,                 -- indica se haverá nova eletrocalha
    q5_novo_eletroduto BOOLEAN,                  -- indica se haverá novo eletroduto
    q5_novo_rack BOOLEAN,                        -- indica se haverá novo rack
    q5_instalacao_eletrica BOOLEAN,              -- indica se haverá adequação/instalação elétrica
    q5_nobreak BOOLEAN,                          -- indica se haverá nobreak
    q5_serralheria BOOLEAN,                      -- indica se haverá serviços de serralheria
    q5_eletrocalha_modelo TEXT,                  -- modelo/descrição da eletrocalha
    q5_eletrocalha_qtd INTEGER,                  -- quantidade de eletrocalhas
    q5_eletroduto_modelo TEXT,                   -- modelo/descrição do eletroduto
    q5_eletroduto_qtd INTEGER,                   -- quantidade de eletrodutos
    q5_rack_modelo TEXT,                         -- modelo/descrição do rack
    q5_rack_qtd INTEGER,                         -- quantidade de racks
    q5_nobreak_modelo TEXT,                      -- modelo/descrição do nobreak
    q5_nobreak_qtd INTEGER,                      -- quantidade de nobreaks
    q5_serralheria_descricao TEXT,               -- descrição detalhada da serralheria necessária
    q5_instalacao_eletrica_obs TEXT,             -- observações adicionais sobre a instalação elétrica

    -- Localização / Referências
    localizacao_imagem1_url TEXT,
    localizacao_imagem2_url TEXT,

    -- Pré-requisitos
    pre_trabalho_altura BOOLEAN,
    pre_plataforma BOOLEAN,
    pre_plataforma_modelo TEXT,
    pre_plataforma_dias INTEGER,
    pre_fora_horario_comercial BOOLEAN,
    pre_veiculo_nortetel BOOLEAN,
    pre_container_materiais BOOLEAN,

    -- Novos campos - dias normais por função
    encarregado_dias INTEGER,
    instalador_dias INTEGER,
    auxiliar_dias INTEGER,
    tecnico_de_instalacao_dias INTEGER,
    tecnico_em_seguranca_dias INTEGER,

    -- Novos campos - horas extras por função
    encarregado_hora_extra INTEGER,
    instalador_hora_extra INTEGER,
    auxiliar_hora_extra INTEGER,
    tecnico_de_instalacao_hora_extra INTEGER,
    tecnico_em_seguranca_hora_extra INTEGER,

    -- Novos campos - trabalho em domingos/feriados por função
    encarregado_trabalho_domingo INTEGER,
    instalador_trabalho_domingo INTEGER,
    auxiliar_trabalho_domingo INTEGER,
    tecnico_de_instalacao_trabalho_domingo INTEGER,
    tecnico_em_seguranca_trabalho_domingo INTEGER,

    -- Novos campos - alimentação
    almoco_qtd INTEGER,
    lanche_qtd INTEGER,

    -- Novos campos - cronograma e prazos (espelho dos antigos 'prazo_*')
    cronograma_execucao BOOLEAN,
    dias_instalacao INTEGER,
    as_built BOOLEAN,
    dias_entrega_relatorio INTEGER,
    art BOOLEAN,
    tipo_formulario VARCHAR(50),

    -- Status e controle
    status VARCHAR(30) NOT NULL DEFAULT 'aberto',
    criado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE avaliacoes_equipamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE,
    equipamento TEXT NOT NULL,
    modelo TEXT,
    quantidade INTEGER NOT NULL,
    fabricante TEXT
);

CREATE TABLE avaliacoes_fotos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- identificador único da foto
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE, -- avaliação à qual a foto pertence
    secao VARCHAR(50) NOT NULL,                                  -- seção lógica (ex.: 'q2_switch')
    descricao TEXT,                                              -- descrição opcional da foto
    arquivo_url TEXT NOT NULL                                    -- URL ou caminho lógico da imagem
);

CREATE TABLE avaliacoes_outros_recursos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE,
    descricao TEXT NOT NULL,
    quantidade INTEGER NOT NULL
);

CREATE TABLE avaliacoes_auditoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id INTEGER NOT NULL REFERENCES avaliacoes(id) ON DELETE CASCADE,
    usuario VARCHAR(255),
    acao VARCHAR(50) NOT NULL,
    detalhes TEXT,
    data_hora TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios_auditoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_alvo_id INTEGER NOT NULL REFERENCES usuarios(id),
    usuario_acao_id INTEGER REFERENCES usuarios(id),
    acao VARCHAR(50) NOT NULL,
    detalhes TEXT,
    data_hora TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);